<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KhFsRJO' shared service.

return $this->privates['.service_locator.KhFsRJO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WariController::addPartenaire' => ['privates', '.service_locator.Z5uHcld', 'get_ServiceLocator_Z5uHcldService.php', true],
    'App\\Controller\\WariController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\WariController:addPartenaire' => ['privates', '.service_locator.Z5uHcld', 'get_ServiceLocator_Z5uHcldService.php', true],
    'App\\Controller\\WariController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\WariController::addPartenaire' => '?',
    'App\\Controller\\WariController::setViewHandler' => '?',
    'App\\Controller\\WariController:addPartenaire' => '?',
    'App\\Controller\\WariController:setViewHandler' => '?',
]);
