<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.N5g3zZJ' shared service.

return $this->privates['.service_locator.N5g3zZJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::admin' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController::AjoutP' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\WariController::Depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController::bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:admin' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController:AjoutP' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\WariController:Depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController:bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\SecurityController::admin' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\WariController::AjoutP' => '?',
    'App\\Controller\\WariController::Depot' => '?',
    'App\\Controller\\WariController::bloquerPartenaie' => '?',
    'App\\Controller\\WariController::setViewHandler' => '?',
    'App\\Controller\\SecurityController:admin' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\WariController:AjoutP' => '?',
    'App\\Controller\\WariController:Depot' => '?',
    'App\\Controller\\WariController:bloquerPartenaie' => '?',
    'App\\Controller\\WariController:setViewHandler' => '?',
]);
