<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ppx1O2A' shared service.

return $this->privates['.service_locator.Ppx1O2A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController::ajoutP' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\WariController::bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\WariController:ajoutP' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\WariController:bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\WariController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\WariController::ajoutP' => '?',
    'App\\Controller\\WariController::bloquerPartenaie' => '?',
    'App\\Controller\\WariController::setViewHandler' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\WariController:ajoutP' => '?',
    'App\\Controller\\WariController:bloquerPartenaie' => '?',
    'App\\Controller\\WariController:setViewHandler' => '?',
]);
