<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZdxdfl\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZdxdfl/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQZdxdfl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQZdxdfl\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerQZdxdfl\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'QZdxdfl',
    'container.build_id' => '0986359f',
    'container.build_time' => 1564086885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZdxdfl');
