<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQFxolx\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQFxolx/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRQFxolx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRQFxolx\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerRQFxolx\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'RQFxolx',
    'container.build_id' => '4c1df94e',
    'container.build_time' => 1564052597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQFxolx');
