<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCJBMQzo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCJBMQzo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCJBMQzo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCJBMQzo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCJBMQzo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CJBMQzo',
    'container.build_id' => '217bca7b',
    'container.build_time' => 1564574029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCJBMQzo');
