<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4UpkkY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4UpkkY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK4UpkkY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK4UpkkY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK4UpkkY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K4UpkkY',
    'container.build_id' => 'd87c0db3',
    'container.build_time' => 1563900450,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4UpkkY');
