<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOG7mZJN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOG7mZJN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOG7mZJN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOG7mZJN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOG7mZJN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OG7mZJN',
    'container.build_id' => '09144075',
    'container.build_time' => 1564563945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOG7mZJN');
